#ifndef __game3_1_script__
#define __game3_1_script__
	float lift_025_051_ceiling_state = 8;
	float ENTRY_TRIGGER_37_49_01_0165_triggered = 0;
	float DEATH_WATCH_TRIGGER_44_48_01_0475_triggered = 0;
	float lift_029_047_ceiling_state = 16;
	float NULL_TRIGGER_21_46_01_0597_state = 1;
	float DEATH_WATCH_TRIGGER_21_45_01_0562_triggered = 0;
	float ENTRY_TRIGGER_26_45_01_0585_triggered = 0;
	float NULL_TRIGGER_31_45_01_0344_triggered = 0;
	float ENTRY_TRIGGER_32_45_01_0184_triggered = 0;
	float NULL_TRIGGER_21_44_01_0557_state = 1;
	float NULL_TRIGGER_25_44_01_0595_state = 1;
	float NULL_TRIGGER_18_43_01_0237_state = 1;
	float lift_033_040_floor_state = 8;
	float NULL_TRIGGER_38_39_01_0628_triggered = 0;
	float LEVER_49_39_01_0365_state = 1;
	float ENTRY_TRIGGER_15_37_01_0727_triggered = 0;
	float ENTRY_TRIGGER_19_37_01_0681_triggered = 0;
	float ENTRY_TRIGGER_17_36_01_0498_triggered = 0;
	float NULL_TRIGGER_19_36_01_0063_state = 1;
	float lift_019_037_floor_state = 16;
	float NULL_TRIGGER_17_35_01_0024_triggered = 0;
	float ENTRY_TRIGGER_39_31_01_0714_state = 1;
	float lift_039_031_floor_state = 22;
	float lift_030_028_floor_state = 8;
	float ENTRY_TRIGGER_30_28_01_0158_state = 1;
	float lift_032_025_ceiling_state = 20;
	float NULL_TRIGGER_33_25_01_0354_state = 1;
	float lift_033_025_ceiling_state = 20;
	float lift_034_025_ceiling_state = 20;
	float ENTRY_TRIGGER_46_25_01_0606_triggered = 0;
	float LEVEL_ENTRY_TRIGGER_31_23_01_0695_triggered = 0;
	float ENTRY_TRIGGER_19_20_01_0713_triggered = 0;
	float ENTRY_TRIGGER_20_20_01_0502_triggered = 0;
	float NULL_TRIGGER_19_19_01_0576_triggered = 0;
	float NULL_TRIGGER_19_19_01_0575_triggered = 0;
	float NULL_TRIGGER_19_19_01_0574_triggered = 0;
	float lift_018_018_floor_state = 8;
	float SWITCH_19_18_01_0126_state = 1;
	float ENTRY_TRIGGER_30_15_01_0150_triggered = 0;
	float NULL_TRIGGER_17_12_01_0163_state = 1;



void start_BUTTON_30_52_01_0541()
{
	float displacement = 51 - lift_025_051_ceiling_state;
	$ceiling_025_051.move( UP, displacement * 15 );
	lift_025_051_ceiling_state = 51 ;

}



void start_SWITCH_20_51_01_0355()
{
	sys.println("Object 0: Not in use");
}



void start_NULL_TRIGGER_20_51_01_0357()
{
	sys.println("Unknown trigger action:21");
}



void start_DEATH_WATCH_TRIGGER_36_50_01_0276()
{
	sys.println("Variable 4097 set. Value 1, 1 operation. Message 0 ");
}



void start_ENTRY_TRIGGER_37_49_01_0165()
{
	if (ENTRY_TRIGGER_37_49_01_0165_triggered == 0)
	{
			ENTRY_TRIGGER_37_49_01_0165_triggered = 1;
	sys.println("Sucess or failMessage");
	}
}



void start_NULL_TRIGGER_41_49_01_0583()
{
}



void start_DEATH_WATCH_TRIGGER_44_49_01_0445()
{
	$sys.wait(0);
	$runscript_NULL_TRIGGER_45_49_01_0506.activate($player1);
	$sys.wait(0);
	$runscript_NULL_TRIGGER_46_49_01_0375.activate($player1);
	$sys.wait(0);
	$runscript_NULL_TRIGGER_46_49_01_0507.activate($player1);
}



void start_NULL_TRIGGER_45_49_01_0506()
{
	sys.println("Variable 4129 set. Value 1, 1 operation. Message 0 ");
}



void start_NULL_TRIGGER_46_49_01_0507()
{
	sys.println("Change state.");
}



void start_NULL_TRIGGER_46_49_01_0375()
{
	sys.println("Change state.");
}



void start_DEATH_WATCH_TRIGGER_44_48_01_0475()
{
	if (DEATH_WATCH_TRIGGER_44_48_01_0475_triggered == 0)
	{
			DEATH_WATCH_TRIGGER_44_48_01_0475_triggered = 1;
	$sys.wait(80);
	$runscript_NULL_TRIGGER_45_48_01_0645.activate($player1);
	$sys.wait(0);
	$runscript_NULL_TRIGGER_20_51_01_0357.activate($player1);
	$sys.wait(0);
	$runscript_NULL_TRIGGER_31_45_01_0344.activate($player1);
	}
}



void start_NULL_TRIGGER_45_48_01_0645()
{
	sys.println("You got mail:2459");
	$player1.addInvItem($NULL_TRIGGER_45_48_01_0645_email);

$data_reader_trigger.setKey("snd_say","shock_audio_log_2459");
$data_reader_trigger.activate($player1);
}



void start_ENTRY_TRIGGER_27_47_01_0598()
{
	float displacement = 24 - lift_029_047_ceiling_state;
	$ceiling_029_047.move( UP, displacement * 15 );
	lift_029_047_ceiling_state = 24 ;

}



void start_REPULSOR_35_47_01_0579()
{
}



void start_EMAIL_18_46_01_0505()
{

$data_reader_trigger.setKey("snd_say","shock_audio_log_2513");
$data_reader_trigger.activate($player1);
}



void start_NULL_TRIGGER_21_46_01_0597()
{
	if (NULL_TRIGGER_21_46_01_0597_state == 1)
		{
		$runscript_NULL_TRIGGER_21_46_01_0590.activate($player1);
		NULL_TRIGGER_21_46_01_0597_state = 0;
		}
	else
		{
		$runscript_NULL_TRIGGER_21_46_01_0591.activate($player1);

		NULL_TRIGGER_21_46_01_0597_state = 1 ;
		}
}



void start_NULL_TRIGGER_21_46_01_0591()
{
	sys.println("Changing FORCE_DOOR_23_45_01_0553 to a FORCE_DOOR");
}



void start_NULL_TRIGGER_21_46_01_0590()
{
	sys.println("Changing FORCE_DOOR_23_45_01_0553 to a GREAT_LORD_SNAQUEOTRAHN");
}



void start_NULL_TRIGGER_12_45_01_0602()
{
	sys.println("Lighting control cp1=603 cp2=602");
}



void start_DEATH_WATCH_TRIGGER_21_45_01_0562()
{
	if (DEATH_WATCH_TRIGGER_21_45_01_0562_triggered == 0)
	{
			DEATH_WATCH_TRIGGER_21_45_01_0562_triggered = 1;
	$sys.wait(0);
	$runscript_NULL_TRIGGER_25_44_01_0594.activate($player1);
	$sys.wait(0);
	$runscript_NULL_TRIGGER_21_45_01_0588.activate($player1);
	}
}



void start_NULL_TRIGGER_21_45_01_0563()
{
	sys.println("Sucess or failMessage");
}



void start_NULL_TRIGGER_21_45_01_0587()
{
	sys.println("Variable 28 set. Value 1, 0 operation. Message 0 ");
}



void start_NULL_TRIGGER_21_45_01_0588()
{
	sys.println("Variable 28 set. Value 0, 0 operation. Message 0 ");
}



void start_BUTTON_23_45_01_0592()
{
	sys.println("Action activate by switch:BUTTON_23_45_01_0592)");
	$sys.wait(0);
	$runscript_NULL_TRIGGER_21_46_01_0597.activate($player1);
}



void start_BUTTON_24_45_01_0558()
{
	sys.println("Action activate by switch:BUTTON_24_45_01_0558)");
	$sys.wait(0);
	$runscript_NULL_TRIGGER_21_46_01_0597.activate($player1);
}



void start_ENTRY_TRIGGER_26_45_01_0585()
{
	if (ENTRY_TRIGGER_26_45_01_0585_triggered == 0)
	{
			ENTRY_TRIGGER_26_45_01_0585_triggered = 1;
	$sys.wait(0);
	$runscript_NULL_TRIGGER_21_45_01_0563.activate($player1);
	$sys.wait(0);
	$runscript_NULL_TRIGGER_25_44_01_0556.activate($player1);
	$sys.wait(0);
	$runscript_NULL_TRIGGER_21_45_01_0587.activate($player1);
	}
}



void start_BUTTON_26_45_01_0593()
{
	sys.println("Action activate by switch:BUTTON_26_45_01_0593)");
	$sys.wait(0);
	$runscript_NULL_TRIGGER_21_44_01_0557.activate($player1);
}



void start_BUTTON_27_45_01_0586()
{
	sys.println("Action activate by switch:BUTTON_27_45_01_0586)");
	$sys.wait(0);
	$runscript_NULL_TRIGGER_25_44_01_0595.activate($player1);
}



void start_BUTTON_27_45_01_0555()
{
	sys.println("Action activate by switch:BUTTON_27_45_01_0555)");
	$sys.wait(0);
	$runscript_NULL_TRIGGER_21_44_01_0557.activate($player1);
}



void start_NULL_TRIGGER_31_45_01_0344()
{
	if (NULL_TRIGGER_31_45_01_0344_triggered == 0)
	{
			NULL_TRIGGER_31_45_01_0344_triggered = 1;
	sys.println("Spawn");
	}
}



void start_ENTRY_TRIGGER_32_45_01_0184()
{
	if (ENTRY_TRIGGER_32_45_01_0184_triggered == 0)
	{
			ENTRY_TRIGGER_32_45_01_0184_triggered = 1;
	sys.println("Sucess or failMessage");
	}
}



void start_NULL_TRIGGER_21_44_01_0557()
{
	if (NULL_TRIGGER_21_44_01_0557_state == 1)
		{
		$runscript_NULL_TRIGGER_21_44_01_0596.activate($player1);
		NULL_TRIGGER_21_44_01_0557_state = 0;
		}
	else
		{
		$runscript_NULL_TRIGGER_21_44_01_0589.activate($player1);

		NULL_TRIGGER_21_44_01_0557_state = 1 ;
		}
}



void start_NULL_TRIGGER_21_44_01_0596()
{
	sys.println("Changing FORCE_DOOR_27_45_01_0552 to a GREAT_LORD_SNAQUEOTRAHN");
}



void start_NULL_TRIGGER_21_44_01_0589()
{
	sys.println("Changing FORCE_DOOR_27_45_01_0552 to a FORCE_DOOR");
}



void start_NULL_TRIGGER_25_44_01_0595()
{
	if (NULL_TRIGGER_25_44_01_0595_state == 1)
		{
		$runscript_NULL_TRIGGER_25_44_01_0594.activate($player1);
		NULL_TRIGGER_25_44_01_0595_state = 0;
		}
	else
		{
		$runscript_NULL_TRIGGER_25_44_01_0556.activate($player1);

		NULL_TRIGGER_25_44_01_0595_state = 1 ;
		}
}



void start_NULL_TRIGGER_25_44_01_0594()
{
	sys.println("Changing FORCE_DOOR_28_44_01_0551 to a GREAT_LORD_SNAQUEOTRAHN");
}



void start_NULL_TRIGGER_25_44_01_0556()
{
	sys.println("Changing FORCE_DOOR_28_44_01_0551 to a FORCE_DOOR");
}



void start_BUTTON_28_44_01_0554()
{
	sys.println("Action activate by switch:BUTTON_28_44_01_0554)");
	$sys.wait(0);
	$runscript_NULL_TRIGGER_25_44_01_0595.activate($player1);
}



void start_NULL_TRIGGER_29_44_01_0356()
{
}



void start_SWITCH_14_43_01_0603()
{
	sys.println("Object 0: Not in use");
}



void start_NULL_TRIGGER_18_43_01_0237()
{
	if (NULL_TRIGGER_18_43_01_0237_state == 1)
		{
		$runscript_NULL_TRIGGER_19_42_01_0539.activate($player1);
		NULL_TRIGGER_18_43_01_0237_state = 0;
		}
	else
		{
		$runscript_NULL_TRIGGER_19_42_01_0540.activate($player1);

		NULL_TRIGGER_18_43_01_0237_state = 1 ;
		}
}



void start_NULL_TRIGGER_18_43_01_0397()
{
	sys.println("Variable 100 set. Value 0, 0 operation. Message 0 ");
}



void start_NULL_TRIGGER_18_43_01_0160()
{
	sys.println("Variable 100 set. Value 1, 0 operation. Message 0 ");
}



void start_LEVER_18_43_01_0227()
{
	sys.println("Action activate by switch:LEVER_18_43_01_0227)");
	$sys.wait(0);
	$runscript_NULL_TRIGGER_18_43_01_0237.activate($player1);
}



void start_PLAYER_DEATH_TRIGGER_19_43_01_0230()
{
	$sys.wait(0);
	$runscript_NULL_TRIGGER_19_43_01_0229.activate($player1);
	$sys.wait(0);
	$runscript_NULL_TRIGGER_19_43_01_0228.activate($player1);
}



void start_NULL_TRIGGER_19_43_01_0229()
{
	sys.println("Teleporting to 18 42 147 ");
}



void start_NULL_TRIGGER_19_43_01_0228()
{
	sys.println("You live again. Or maybe get turned into a cyborg.");
}



void start_NULL_TRIGGER_42_43_01_0604()
{
	sys.println("Lighting control cp1=605 cp2=604");
}



void start_EMAIL_16_42_01_0316()
{

$data_reader_trigger.setKey("snd_say","shock_audio_log_2506");
$data_reader_trigger.activate($player1);
}



void start_NULL_TRIGGER_19_42_01_0540()
{
	$sys.wait(0);
	$runscript_NULL_TRIGGER_19_42_01_0538.activate($player1);
	$sys.wait(0);
	$runscript_NULL_TRIGGER_18_43_01_0397.activate($player1);
}



void start_NULL_TRIGGER_19_42_01_0539()
{
	$sys.wait(0);
	$runscript_NULL_TRIGGER_19_42_01_0537.activate($player1);
	$sys.wait(0);
	$runscript_NULL_TRIGGER_18_43_01_0160.activate($player1);
}



void start_NULL_TRIGGER_19_42_01_0538()
{
	sys.println("Sucess or failMessage");
}



void start_NULL_TRIGGER_19_42_01_0537()
{
	sys.println("Sucess or failMessage");
}



void start_REPULSOR_26_42_01_0451()
{
	sys.println("Do nothing. Or maybe a default action.");
}



void start_SWITCH_12_41_01_0525()
{
	sys.println("Action activate by switch:SWITCH_12_41_01_0525)");
	$sys.wait(0);
	$a_lock_014_040.activate($player1);
}



void start_REPULSOR_30_41_01_0055()
{
	$sys.wait(0);
	sys.println("Object 1: Not in use");
}



void start_SWITCH_30_40_01_0450()
{
	sys.println("Action activate by switch:SWITCH_30_40_01_0450)");
	$sys.wait(0);
	$a_lock_031_038.activate($player1);
}



void start_ENTRY_TRIGGER_33_40_01_0216()
{
	float displacement = 0 - lift_033_040_floor_state;
	$floor_033_040.move( UP, displacement * 15  );
	lift_033_040_floor_state = 0 ;

}



void start_NULL_TRIGGER_49_40_01_0371()
{
	$sys.wait(0);
	$runscript_NULL_TRIGGER_49_40_01_0370.activate($player1);
	$sys.wait(0);
	$runscript_NULL_TRIGGER_49_40_01_0326.activate($player1);
}



void start_NULL_TRIGGER_49_40_01_0372()
{
	$sys.wait(0);
	$runscript_NULL_TRIGGER_49_40_01_0217.activate($player1);
	$sys.wait(0);
	$runscript_NULL_TRIGGER_49_40_01_0373.activate($player1);
}



void start_NULL_TRIGGER_49_40_01_0370()
{
	sys.println("Changing ELEPHANT,_JORP_45_38_01_0180 to a FORCE_BRIDGE");
}



void start_NULL_TRIGGER_49_40_01_0326()
{
	sys.println("Changing ELEPHANT,_JORP_45_37_01_0243 to a FORCE_BRIDGE");
}



void start_NULL_TRIGGER_49_40_01_0217()
{
	sys.println("Changing ELEPHANT,_JORP_45_38_01_0180 to a ELEPHANT,_JORP");
}



void start_NULL_TRIGGER_49_40_01_0373()
{
	sys.println("Changing ELEPHANT,_JORP_45_37_01_0243 to a ELEPHANT,_JORP");
}



void start_EMAIL_35_39_01_0317()
{

$data_reader_trigger.setKey("snd_say","shock_audio_log_2510");
$data_reader_trigger.activate($player1);
}



void start_NULL_TRIGGER_38_39_01_0628()
{
	if (NULL_TRIGGER_38_39_01_0628_triggered == 0)
	{
			NULL_TRIGGER_38_39_01_0628_triggered = 1;
	sys.println("You got mail:2485");
	$player1.addInvItem($NULL_TRIGGER_38_39_01_0628_email);

$data_reader_trigger.setKey("snd_say","shock_audio_log_2485");
$data_reader_trigger.activate($player1);
	}
}



void start_NULL_TRIGGER_38_39_01_0320()
{
	sys.println("Unknown trigger action:13");
}



void start_NULL_TRIGGER_38_39_01_0408()
{
	sys.println("Object cloned. 49 (39,38,240)");
}



void start_LEVER_49_39_01_0365()
{
	if (LEVER_49_39_01_0365_state == 1)
		{
		$runscript_NULL_TRIGGER_49_40_01_0371.activate($player1);
		LEVER_49_39_01_0365_state = 0;
		}
	else
		{
		$runscript_NULL_TRIGGER_49_40_01_0372.activate($player1);

		LEVER_49_39_01_0365_state = 1 ;
		}
}



void start_EMERGENCY_LEVER_39_38_01_0627()
{
	sys.println("Action activate by switch:EMERGENCY_LEVER_39_38_01_0627)");
	$sys.wait(0);
	$runscript_NULL_TRIGGER_38_39_01_0628.activate($player1);
	$sys.wait(0);
	$runscript_NULL_TRIGGER_38_39_01_0408.activate($player1);
	$sys.wait(0);
	$runscript_NULL_TRIGGER_38_39_01_0320.activate($player1);
}



void start_CYBERSPACE_TERMINAL_12_37_01_0535()
{
	sys.println("Teleporting to a cyberspace level:14@(8,47,70)");
}



void start_ENTRY_TRIGGER_15_37_01_0727()
{
	if (ENTRY_TRIGGER_15_37_01_0727_triggered == 0)
	{
			ENTRY_TRIGGER_15_37_01_0727_triggered = 1;
	$sys.wait(0);
	$runscript_NULL_TRIGGER_38_39_01_0320.activate($player1);
	$sys.wait(0);
	$runscript_NULL_TRIGGER_38_39_01_0408.activate($player1);
	}
}



void start_ELEVATOR_PANEL_15_37_01_0030()
{
	sys.println("Moving levels possible panels are: 193, 30, 0 ");
}



void start_EMAIL_18_37_01_0021()
{

$data_reader_trigger.setKey("snd_say","shock_audio_log_2514");
$data_reader_trigger.activate($player1);
}



void start_LARGE_BUTTON_18_37_01_0016()
{
	sys.println("Action activate by switch:LARGE_BUTTON_18_37_01_0016)");
	$sys.wait(0);
	$runscript_NULL_TRIGGER_19_36_01_0063.activate($player1);
}



void start_ENTRY_TRIGGER_19_37_01_0681()
{
	if (ENTRY_TRIGGER_19_37_01_0681_triggered == 0)
	{
			ENTRY_TRIGGER_19_37_01_0681_triggered = 1;
	sys.println("You got mail:2462");
	$player1.addInvItem($ENTRY_TRIGGER_19_37_01_0681_email);

$data_reader_trigger.setKey("snd_say","shock_audio_log_2462");
$data_reader_trigger.activate($player1);
	}
}



void start_LARGE_BUTTON_20_37_01_0220()
{
	sys.println("Action activate by switch:LARGE_BUTTON_20_37_01_0220)");
	$sys.wait(0);
	$runscript_NULL_TRIGGER_19_36_01_0063.activate($player1);
}



void start_ENTRY_TRIGGER_17_36_01_0498()
{
	if (ENTRY_TRIGGER_17_36_01_0498_triggered == 0)
	{
			ENTRY_TRIGGER_17_36_01_0498_triggered = 1;
	sys.println("Sucess or failMessage");
	}
}



void start_NULL_TRIGGER_19_36_01_0063()
{
	if (NULL_TRIGGER_19_36_01_0063_state == 1)
		{
		$runscript_NULL_TRIGGER_19_36_01_0007.activate($player1);
		NULL_TRIGGER_19_36_01_0063_state = 0;
		}
	else
		{
		$runscript_NULL_TRIGGER_19_36_01_0009.activate($player1);

		NULL_TRIGGER_19_36_01_0063_state = 1 ;
		}
}



void start_NULL_TRIGGER_19_36_01_0007()
{
	float displacement = 8 - lift_019_037_floor_state;
	$floor_019_037.move( UP, displacement * 15  );
	lift_019_037_floor_state = 8 ;

}



void start_NULL_TRIGGER_19_36_01_0009()
{
	float displacement = 16 - lift_019_037_floor_state;
	$floor_019_037.move( UP, displacement * 15  );
	lift_019_037_floor_state = 16 ;

}



void start_NULL_TRIGGER_31_36_01_0584()
{
}



void start_NULL_TRIGGER_17_35_01_0024()
{
	if (NULL_TRIGGER_17_35_01_0024_triggered == 0)
	{
			NULL_TRIGGER_17_35_01_0024_triggered = 1;
	sys.println("Variable 1 set. Value 0, 0 operation. Message 0 ");
	}
}



void start_NULL_TRIGGER_17_35_01_0023()
{
	$sys.wait(0);
	$a_lock_017_035.activate($player1);
}



void start_LEVER_17_35_01_0130()
{
	sys.println("Action activate by switch:LEVER_17_35_01_0130)");
	$sys.wait(0);
	$runscript_NULL_TRIGGER_17_35_01_0024.activate($player1);
	$sys.wait(0);
	$runscript_NULL_TRIGGER_17_35_01_0023.activate($player1);
}



void start_CRITTER_AI_HINT_28_34_01_0312()
{
	$sys.wait(0);
	$CRITTER_AI_HINT_35_34_01_0308.activate($player1);
}



void start_CRITTER_AI_HINT_35_34_01_0308()
{
	$sys.wait(0);
	$CRITTER_AI_HINT_36_30_01_0309.activate($player1);
}



void start_ENERGY_CHARGE_STATION_38_34_01_0679()
{
	sys.println("Charging up: 255 , Security level? 48");
}



void start_NULL_TRIGGER_17_33_01_0601()
{
	sys.println("Lighting control cp1=600 cp2=601");
}



void start_NULL_TRIGGER_37_33_01_0206()
{
}



void start_LARGE_BUTTON_40_32_01_0159()
{
	sys.println("Action activate by switch:LARGE_BUTTON_40_32_01_0159)");
	$sys.wait(0);
	$ENTRY_TRIGGER_39_31_01_0714.activate($player1);
}



void start_NULL_TRIGGER_11_31_01_0655()
{
	$sys.wait(0);
	$a_lock_011_032.activate($player1);
}



void start_NULL_TRIGGER_11_31_01_0654()
{
	$sys.wait(0);
	$a_lock_011_029.activate($player1);
}



void start_BUTTON_17_31_01_0701()
{
	sys.println("Lighting control cp1=3 cp2=701");
}



void start_NULL_TRIGGER_19_31_01_0600()
{
}



void start_BUTTON_33_31_01_0662()
{
	sys.println("Action change state by switch:BUTTON_33_31_01_0662)");
	$runscript_REPULSOR_31_30_01_0668.activate($player1);
}



void start_ENTRY_TRIGGER_39_31_01_0714()
{
	if (ENTRY_TRIGGER_39_31_01_0714_state == 1)
		{
		$runscript_NULL_TRIGGER_39_31_01_0215.activate($player1);
		ENTRY_TRIGGER_39_31_01_0714_state = 0;
		}
	else
		{
		$runscript_NULL_TRIGGER_39_31_01_0214.activate($player1);

		ENTRY_TRIGGER_39_31_01_0714_state = 1 ;
		}
}



void start_NULL_TRIGGER_39_31_01_0215()
{
	float displacement = 8 - lift_039_031_floor_state;
	$floor_039_031.move( UP, displacement * 15  );
	lift_039_031_floor_state = 8 ;

}



void start_NULL_TRIGGER_39_31_01_0214()
{
	float displacement = 24 - lift_039_031_floor_state;
	$floor_039_031.move( UP, displacement * 15  );
	lift_039_031_floor_state = 24 ;

}



void start_LEVEL_ENTRY_TRIGGER_11_30_01_0653()
{
	$sys.wait(0);
	$runscript_NULL_TRIGGER_11_31_01_0654.activate($player1);
	$sys.wait(0);
	$runscript_NULL_TRIGGER_11_31_01_0655.activate($player1);
}



void start_BUTTON_27_30_01_0700()
{
	sys.println("Lighting control cp1=3 cp2=700");
}



void start_NULL_TRIGGER_31_30_01_0708()
{
	sys.println("Sucess or failMessage");
}



void start_REPULSOR_31_30_01_0668()
{
	$sys.wait(0);
	sys.println("Object 1: Not in use");
}



void start_BUTTON_32_30_01_0529()
{
	sys.println("Action change state by switch:BUTTON_32_30_01_0529)");
	$runscript_REPULSOR_31_30_01_0668.activate($player1);
}



void start_ACCESS_PANEL_32_30_01_0682()
{
	sys.println("Puzzle type was: 0");
	$a_lock_031_038.activate($player1);
}



void start_CRITTER_AI_HINT_36_30_01_0309()
{
	$sys.wait(0);
	$CRITTER_AI_HINT_36_27_01_0310.activate($player1);
}



void start_LARGE_BUTTON_38_30_01_0110()
{
	sys.println("Action activate by switch:LARGE_BUTTON_38_30_01_0110)");
	$sys.wait(0);
	$ENTRY_TRIGGER_39_31_01_0714.activate($player1);
}



void start_NULL_TRIGGER_39_30_01_0207()
{
}



void start_NULL_TRIGGER_41_30_01_0208()
{
	sys.println("Lighting control cp1=207 cp2=206");
}



void start_EMAIL_12_29_01_0399()
{

$data_reader_trigger.setKey("snd_say","shock_audio_log_2511");
$data_reader_trigger.activate($player1);
}



void start_LEVER_30_29_01_0432()
{
	sys.println("Action activate by switch:LEVER_30_29_01_0432)");
	$sys.wait(0);
	$ENTRY_TRIGGER_30_28_01_0158.activate($player1);
}



void start_NULL_TRIGGER_34_29_01_0683()
{
	sys.println("Do nothing. Or maybe a default action.");
}



void start_EMAIL_51_29_01_0465()
{

$data_reader_trigger.setKey("snd_say","shock_audio_log_2512");
$data_reader_trigger.activate($player1);
}



void start_SWITCH_20_28_01_0093()
{
	sys.println("Object 0: Not in use");
}



void start_NULL_TRIGGER_24_28_01_0129()
{
}



void start_NULL_TRIGGER_26_28_01_0152()
{
}



void start_NULL_TRIGGER_30_28_01_0200()
{
	float displacement = 0 - lift_030_028_floor_state;
	$floor_030_028.move( UP, displacement * 15  );
	lift_030_028_floor_state = 0 ;

}



void start_NULL_TRIGGER_30_28_01_0027()
{
	float displacement = 8 - lift_030_028_floor_state;
	$floor_030_028.move( UP, displacement * 15  );
	lift_030_028_floor_state = 8 ;

}



void start_ENTRY_TRIGGER_30_28_01_0158()
{
	if (ENTRY_TRIGGER_30_28_01_0158_state == 1)
		{
		$runscript_NULL_TRIGGER_30_28_01_0200.activate($player1);
		ENTRY_TRIGGER_30_28_01_0158_state = 0;
		}
	else
		{
		$runscript_NULL_TRIGGER_30_28_01_0027.activate($player1);

		ENTRY_TRIGGER_30_28_01_0158_state = 1 ;
		}
}



void start_NULL_TRIGGER_46_28_01_0114()
{
	$sys.wait(0);
	$runscript_NULL_TRIGGER_46_28_01_0298.activate($player1);
	$sys.wait(0);
	$runscript_NULL_TRIGGER_46_28_01_0299.activate($player1);
}



void start_NULL_TRIGGER_46_28_01_0299()
{
	sys.println("Changing ELEPHANT,_JORP_46_29_01_0290 to a FORCE_BRIDGE");
}



void start_NULL_TRIGGER_46_28_01_0298()
{
	sys.println("Changing ELEPHANT,_JORP_46_30_01_0292 to a FORCE_BRIDGE");
}



void start_ACCESS_PANEL_47_28_01_0259()
{
	sys.println("Puzzle type was: 0");
	$runscript_NULL_TRIGGER_46_28_01_0114.activate($player1);
}



void start_EMAIL_12_27_01_0474()
{

$data_reader_trigger.setKey("snd_say","shock_audio_log_2517");
$data_reader_trigger.activate($player1);
}



void start_NULL_TRIGGER_26_27_01_0252()
{
	sys.println("Lighting control cp1=93 cp2=252");
}



void start_CRITTER_AI_HINT_28_27_01_0311()
{
	$sys.wait(0);
	$CRITTER_AI_HINT_28_34_01_0312.activate($player1);
}



void start_CRITTER_AI_HINT_36_27_01_0310()
{
	$sys.wait(0);
	$CRITTER_AI_HINT_28_27_01_0311.activate($player1);
}



void start_REPULSOR_43_27_01_0366()
{
	$sys.wait(0);
	sys.println("Object 1: Not in use");
}



void start_ENERGY_CHARGE_STATION_28_26_01_0411()
{
	sys.println("Charging up: 255 , Security level? 60");
}



void start_LARGE_BUTTON_34_26_01_0536()
{
	sys.println("Action activate by switch:LARGE_BUTTON_34_26_01_0536)");
	$sys.wait(0);
	$runscript_NULL_TRIGGER_33_25_01_0354.activate($player1);
}



void start_SWITCH_55_26_01_0605()
{
	sys.println("Object 0: Not in use");
}



void start_NULL_TRIGGER_27_25_01_0151()
{
	sys.println("Lighting control cp1=66 cp2=151");
}



void start_NULL_TRIGGER_32_25_01_0054()
{
	float displacement = 8 - lift_032_025_ceiling_state;
	$ceiling_032_025.move( UP, displacement * 15 );
	lift_032_025_ceiling_state = 8 ;

}



void start_NULL_TRIGGER_32_25_01_0109()
{
	float displacement = 25 - lift_032_025_ceiling_state;
	$ceiling_032_025.move( UP, displacement * 15 );
	lift_032_025_ceiling_state = 25 ;

}



void start_NULL_TRIGGER_33_25_01_0354()
{
	if (NULL_TRIGGER_33_25_01_0354_state == 1)
		{
		$runscript_NULL_TRIGGER_33_25_01_0012.activate($player1);
		NULL_TRIGGER_33_25_01_0354_state = 0;
		}
	else
		{
		$runscript_NULL_TRIGGER_33_25_01_0032.activate($player1);

		NULL_TRIGGER_33_25_01_0354_state = 1 ;
		}
}



void start_NULL_TRIGGER_33_25_01_0034()
{
	float displacement = 25 - lift_033_025_ceiling_state;
	$ceiling_033_025.move( UP, displacement * 15 );
	lift_033_025_ceiling_state = 25 ;

}



void start_NULL_TRIGGER_33_25_01_0012()
{
	$sys.wait(0);
	$runscript_NULL_TRIGGER_32_25_01_0054.activate($player1);
	$sys.wait(0);
	$runscript_NULL_TRIGGER_33_25_01_0031.activate($player1);
	$sys.wait(0);
	$runscript_NULL_TRIGGER_34_25_01_0033.activate($player1);
}



void start_NULL_TRIGGER_33_25_01_0032()
{
	$sys.wait(0);
	$runscript_NULL_TRIGGER_32_25_01_0109.activate($player1);
	$sys.wait(0);
	$runscript_NULL_TRIGGER_33_25_01_0034.activate($player1);
	$sys.wait(0);
	$runscript_NULL_TRIGGER_34_25_01_0053.activate($player1);
}



void start_NULL_TRIGGER_33_25_01_0031()
{
	float displacement = 8 - lift_033_025_ceiling_state;
	$ceiling_033_025.move( UP, displacement * 15 );
	lift_033_025_ceiling_state = 8 ;

}



void start_NULL_TRIGGER_34_25_01_0033()
{
	float displacement = 8 - lift_034_025_ceiling_state;
	$ceiling_034_025.move( UP, displacement * 15 );
	lift_034_025_ceiling_state = 8 ;

}



void start_NULL_TRIGGER_34_25_01_0053()
{
	float displacement = 25 - lift_034_025_ceiling_state;
	$ceiling_034_025.move( UP, displacement * 15 );
	lift_034_025_ceiling_state = 25 ;

}



void start_ENTRY_TRIGGER_46_25_01_0606()
{
	if (ENTRY_TRIGGER_46_25_01_0606_triggered == 0)
	{
			ENTRY_TRIGGER_46_25_01_0606_triggered = 1;
	$sys.wait(0);
	$runscript_NULL_TRIGGER_47_25_01_0607.activate($player1);
	}
}



void start_NULL_TRIGGER_47_25_01_0607()
{
	sys.println("Unknown trigger action:11");
}



void start_NULL_TRIGGER_10_24_01_0353()
{
}



void start_ENTRY_TRIGGER_26_24_01_0146()
{
	$sys.wait(0);
	$runscript_NULL_TRIGGER_29_24_01_0066.activate($player1);
}



void start_NULL_TRIGGER_29_24_01_0209()
{
	$sys.wait(0);
	$runscript_NULL_TRIGGER_17_33_01_0601.activate($player1);
	$sys.wait(0);
	$runscript_NULL_TRIGGER_12_45_01_0602.activate($player1);
}



void start_NULL_TRIGGER_29_24_01_0599()
{
	$sys.wait(0);
	$runscript_NULL_TRIGGER_29_13_01_0211.activate($player1);
	$sys.wait(0);
	$runscript_NULL_TRIGGER_17_12_01_0337.activate($player1);
	$sys.wait(0);
	$runscript_NULL_TRIGGER_41_20_01_0236.activate($player1);
	$sys.wait(0);
	$runscript_NULL_TRIGGER_29_24_01_0209.activate($player1);
}



void start_NULL_TRIGGER_29_24_01_0064()
{
	$sys.wait(0);
	$runscript_NULL_TRIGGER_27_25_01_0151.activate($player1);
	$sys.wait(0);
	$runscript_NULL_TRIGGER_26_27_01_0252.activate($player1);
	$sys.wait(0);
	$runscript_NULL_TRIGGER_41_30_01_0208.activate($player1);
	$sys.wait(0);
	$runscript_NULL_TRIGGER_29_24_01_0599.activate($player1);
}



void start_NULL_TRIGGER_29_24_01_0066()
{
	sys.println("Unknown trigger action:11");
}



void start_LEVEL_ENTRY_TRIGGER_30_24_01_0037()
{
	$sys.wait(0);
	$runscript_NULL_TRIGGER_29_24_01_0066.activate($player1);
}



void start_EMAIL_38_24_01_0460()
{

$data_reader_trigger.setKey("snd_say","shock_audio_log_2516");
$data_reader_trigger.activate($player1);
}



void start_LEVEL_ENTRY_TRIGGER_31_23_01_0695()
{
	if (LEVEL_ENTRY_TRIGGER_31_23_01_0695_triggered == 0)
	{
			LEVEL_ENTRY_TRIGGER_31_23_01_0695_triggered = 1;
	sys.println("You live again. Or maybe get turned into a cyborg.");
	}
}



void start_LARGE_BUTTON_35_23_01_0117()
{
	sys.println("Action activate by switch:LARGE_BUTTON_35_23_01_0117)");
	$sys.wait(0);
	$runscript_NULL_TRIGGER_33_25_01_0354.activate($player1);
}



void start_EMAIL_11_22_01_0315()
{

$data_reader_trigger.setKey("snd_say","shock_audio_log_2505");
$data_reader_trigger.activate($player1);
}



void start_NULL_TRIGGER_20_22_01_0141()
{
	sys.println("Lighting control cp1=152 cp2=129");
}



void start_NULL_TRIGGER_21_22_01_0062()
{
	sys.println("Unknown trigger action:11");
}



void start_NULL_TRIGGER_25_22_01_0696()
{
	$sys.wait(0);
	$a_lock_026_024.activate($player1);
	$sys.wait(0);
	$a_lock_026_021.activate($player1);
}



void start_BUTTON_26_22_01_0176()
{
	sys.println("Action activate by switch:BUTTON_26_22_01_0176)");
	$sys.wait(0);
	$a_lock_026_021.activate($player1);
}



void start_EMAIL_33_22_01_0454()
{

$data_reader_trigger.setKey("snd_say","shock_audio_log_2518");
$data_reader_trigger.activate($player1);
}



void start_NULL_TRIGGER_14_21_01_0452()
{
}



void start_NULL_TRIGGER_20_21_01_0205()
{
	$sys.wait(0);
	$runscript_NULL_TRIGGER_41_30_01_0208.activate($player1);
	$sys.wait(0);
	$runscript_NULL_TRIGGER_20_22_01_0141.activate($player1);
	$sys.wait(0);
	$runscript_NULL_TRIGGER_29_13_01_0211.activate($player1);
}



void start_SHODAN_TRIGGER_46_21_01_0483()
{
	$sys.wait(0);
	$HIDDEN_DOOR_46_21_01_0482.activate($player1);
}



void start_ENTRY_TRIGGER_19_20_01_0713()
{
	if (ENTRY_TRIGGER_19_20_01_0713_triggered == 0)
	{
			ENTRY_TRIGGER_19_20_01_0713_triggered = 1;
	sys.println("Variable 145 set. Value 1, 0 operation. Message 0 ");
	}
}



void start_ENTRY_TRIGGER_20_20_01_0502()
{
	if (ENTRY_TRIGGER_20_20_01_0502_triggered == 0)
	{
			ENTRY_TRIGGER_20_20_01_0502_triggered = 1;
	sys.println("You got mail:2441");
	$player1.addInvItem($ENTRY_TRIGGER_20_20_01_0502_email);

$data_reader_trigger.setKey("snd_say","shock_audio_log_2441");
$data_reader_trigger.activate($player1);
	}
}



void start_NULL_TRIGGER_41_20_01_0236()
{
	sys.println("Lighting control cp1=338 cp2=236");
}



void start_NULL_TRIGGER_46_20_01_0139()
{
	sys.println("Do nothing. Or maybe a default action.");
}



void start_NULL_TRIGGER_19_19_01_0576()
{
	if (NULL_TRIGGER_19_19_01_0576_triggered == 0)
	{
			NULL_TRIGGER_19_19_01_0576_triggered = 1;
	$sys.wait(0);
	$runscript_NULL_TRIGGER_19_19_01_0575.activate($player1);
	$sys.wait(0);
	$runscript_NULL_TRIGGER_19_19_01_0574.activate($player1);
	}
}



void start_NULL_TRIGGER_19_19_01_0575()
{
	if (NULL_TRIGGER_19_19_01_0575_triggered == 0)
	{
			NULL_TRIGGER_19_19_01_0575_triggered = 1;
	sys.println("Variable 252 set. Value 1, 0 operation. Message 0 ");
	}
}



void start_NULL_TRIGGER_19_19_01_0574()
{
	if (NULL_TRIGGER_19_19_01_0574_triggered == 0)
	{
			NULL_TRIGGER_19_19_01_0574_triggered = 1;
	sys.println("Lighting control cp1=574 cp2=573");
	}
}



void start_EMAIL_20_19_01_0485()
{

$data_reader_trigger.setKey("snd_say","shock_audio_log_2504");
$data_reader_trigger.activate($player1);
}



void start_KEYPAD_PANEL_20_19_01_0096()
{
	sys.println("You correcty guess the combination code 451");
	$a_lock_020_020.activate($player1);
}



void start_ENTRY_TRIGGER_18_18_01_0573()
{
	$sys.wait(0);
	$runscript_NULL_TRIGGER_17_12_01_0163.activate($player1);
}



void start_NULL_TRIGGER_18_18_01_0112()
{
	float displacement = 0 - lift_018_018_floor_state;
	$floor_018_018.move( UP, displacement * 15  );
	lift_018_018_floor_state = 0 ;

}



void start_NULL_TRIGGER_18_18_01_0113()
{
	float displacement = 8 - lift_018_018_floor_state;
	$floor_018_018.move( UP, displacement * 15  );
	lift_018_018_floor_state = 8 ;

}



void start_SWITCH_19_18_01_0126()
{
	if (SWITCH_19_18_01_0126_state == 1)
		{
		$runscript_NULL_TRIGGER_18_18_01_0112.activate($player1);
		SWITCH_19_18_01_0126_state = 0;
		}
	else
		{
		$runscript_NULL_TRIGGER_18_18_01_0113.activate($player1);

		SWITCH_19_18_01_0126_state = 1 ;
		}
}



void start_NULL_TRIGGER_20_18_01_0006()
{
	$sys.wait(0);
	$runscript_NULL_TRIGGER_20_18_01_0036.activate($player1);
	$sys.wait(0);
	$a_lock_026_021.activate($player1);
}



void start_NULL_TRIGGER_20_18_01_0036()
{
	sys.println("Variable 2 set. Value 1, 0 operation. Message 0 ");
}



void start_ENERGY_CHARGE_STATION_22_18_01_0659()
{
	sys.println("Charging up: 255 , Security level? 48");
}



void start_NULL_TRIGGER_44_18_01_0338()
{
}



void start_NULL_TRIGGER_15_17_01_0578()
{
	sys.println("Do nothing. Or maybe a default action.");
}



void start_ECOLOGY_TRIGGER_16_17_01_0437()
{
	sys.println("Spawn");
}



void start_NULL_TRIGGER_17_17_01_0288()
{
}



void start_ACCESS_PANEL_18_17_01_0577()
{
	sys.println("Puzzle type was: 0");
	$runscript_NULL_TRIGGER_19_19_01_0576.activate($player1);
}



void start_EMAIL_29_17_01_0462()
{

$data_reader_trigger.setKey("snd_say","shock_audio_log_2519");
$data_reader_trigger.activate($player1);
}



void start_LARGE_BUTTON_23_15_01_0289()
{
	sys.println("Lighting control cp1=300 cp2=288");
}



void start_ENTRY_TRIGGER_30_15_01_0150()
{
	if (ENTRY_TRIGGER_30_15_01_0150_triggered == 0)
	{
			ENTRY_TRIGGER_30_15_01_0150_triggered = 1;
	$sys.wait(0);
	$runscript_NULL_TRIGGER_29_14_01_0680.activate($player1);
	}
}



void start_NULL_TRIGGER_26_14_01_0300()
{
}



void start_SWITCH_27_14_01_0210()
{
	sys.println("Object 0: Not in use");
}



void start_NULL_TRIGGER_29_14_01_0680()
{
	sys.println("Unknown trigger action:11");
}



void start_EMAIL_40_14_01_0318()
{

$data_reader_trigger.setKey("snd_say","shock_audio_log_2507");
$data_reader_trigger.activate($player1);
}



void start_BUTTON_27_13_01_0702()
{
	sys.println("Lighting control cp1=2 cp2=707");
}



void start_NULL_TRIGGER_29_13_01_0211()
{
	sys.println("Lighting control cp1=210 cp2=211");
}



void start_NULL_TRIGGER_17_12_01_0163()
{
	if (NULL_TRIGGER_17_12_01_0163_state == 1)
		{
		$runscript_NULL_TRIGGER_18_18_01_0112.activate($player1);
		NULL_TRIGGER_17_12_01_0163_state = 0;
		}
	else
		{
		$runscript_NULL_TRIGGER_18_18_01_0113.activate($player1);

		NULL_TRIGGER_17_12_01_0163_state = 1 ;
		}
}



void start_NULL_TRIGGER_17_12_01_0337()
{
	sys.println("Lighting control cp1=339 cp2=337");
}



void start_KEYPAD_PANEL_23_12_01_0291()
{
	sys.println("You correcty guess the combination code 705");
	$a_lock_023_012.activate($player1);
}



void start_BUTTON_27_11_01_0703()
{
	sys.println("Lighting control cp1=3 cp2=704");
}



void start_EMAIL_38_11_01_0319()
{

$data_reader_trigger.setKey("snd_say","shock_audio_log_2508");
$data_reader_trigger.activate($player1);
}



void start_EMAIL_04_04_01_0321()
{

$data_reader_trigger.setKey("snd_say","shock_audio_log_2509");
$data_reader_trigger.activate($player1);
}



void start_ENTRY_TRIGGER_20_20_01_0502_email()
{

$data_reader_trigger.setKey("snd_say","shock_audio_log_2441");
$data_reader_trigger.activate($player1);

}



void start_NULL_TRIGGER_38_39_01_0628_email()
{

$data_reader_trigger.setKey("snd_say","shock_audio_log_2485");
$data_reader_trigger.activate($player1);

}



void start_NULL_TRIGGER_45_48_01_0645_email()
{

$data_reader_trigger.setKey("snd_say","shock_audio_log_2459");
$data_reader_trigger.activate($player1);

}



void start_ENTRY_TRIGGER_19_37_01_0681_email()
{

$data_reader_trigger.setKey("snd_say","shock_audio_log_2462");
$data_reader_trigger.activate($player1);

}
#endif //__game3_1_script__